"""Minimal owner and accountant workspace portal.

The portal is intentionally a collaboration surface, not a second accounting
database. It exposes only authenticated workspace metadata and keeps invoices,
attachments and financial snapshots out of browser HTML.
"""

from __future__ import annotations


def workspace_portal_html() -> str:
    return """<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>OpsNest Workspace</title><style>
:root{--ink:#132238;--muted:#63738a;--line:#dce5ee;--mint:#087e72;--mint-soft:#e8f7f3;--navy:#102d47;--bg:#f5f8fb;--card:#fff;--warn:#9b6510}
*{box-sizing:border-box}body{margin:0;background:var(--bg);font:15px/1.5 Inter,Segoe UI,Arial,sans-serif;color:var(--ink)}
.shell{max-width:1180px;margin:auto;padding:30px 22px 70px}.top{display:flex;align-items:center;justify-content:space-between;margin-bottom:28px}.brand{display:flex;gap:11px;align-items:center;font-weight:800;font-size:20px}.mark{width:34px;height:34px;border-radius:11px;background:linear-gradient(135deg,#08a898,#075a78);position:relative}.mark:after{content:'N';color:white;position:absolute;left:10px;top:5px;font-weight:900;font-size:20px}.tag{color:var(--mint);font-size:12px;font-weight:800;letter-spacing:.08em;text-transform:uppercase}.card{background:var(--card);border:1px solid var(--line);border-radius:16px;box-shadow:0 8px 26px #102d470c}.login{max-width:510px;margin:8vh auto;padding:30px}.login h1{margin:6px 0;font-size:29px}.muted{color:var(--muted)}label{display:block;font-size:13px;font-weight:700;margin-top:14px}input,select{width:100%;border:1px solid #bdcad7;border-radius:9px;padding:11px 12px;margin-top:5px;font:inherit;background:white;color:var(--ink)}button{border:0;border-radius:9px;padding:11px 15px;font:inherit;font-weight:750;cursor:pointer}.primary{background:var(--mint);color:#fff}.quiet{background:#eef3f7;color:var(--navy)}.link{background:transparent;color:var(--mint);padding:10px 0}.actions{display:flex;gap:8px;align-items:center;margin-top:20px}.error{color:#b42318;margin-top:12px;min-height:22px}.hero{padding:28px;background:linear-gradient(120deg,#10304b,#087e72);color:white;border-radius:18px}.hero h1{font-size:31px;margin:4px 0}.hero p{margin:0;color:#d6f5ee}.grid{display:grid;grid-template-columns:repeat(4,1fr);gap:14px;margin:16px 0}.metric{padding:18px}.metric b{font-size:22px;display:block;margin-top:8px}.metric span{font-size:13px;color:var(--muted)}.two{display:grid;grid-template-columns:1.5fr 1fr;gap:16px}.section{padding:22px}.section h2{font-size:18px;margin:0 0 14px}.module{display:flex;justify-content:space-between;gap:18px;padding:15px 0;border-top:1px solid var(--line)}.module:first-of-type{border-top:0}.module b{display:block}.module p{margin:3px 0 0;color:var(--muted);font-size:13px}.status{height:max-content;border-radius:99px;padding:4px 9px;background:var(--mint-soft);color:#06665d;font-size:12px;font-weight:800;white-space:nowrap}.status.foundation{background:#fff6df;color:var(--warn)}.profile{display:grid;grid-template-columns:1fr 1fr;gap:10px}.profile .wide{grid-column:1/-1}.footer{color:var(--muted);font-size:12px;margin-top:20px}.hidden{display:none!important}@media(max-width:780px){.grid{grid-template-columns:repeat(2,1fr)}.two{grid-template-columns:1fr}.hero h1{font-size:25px}}@media(max-width:460px){.grid{grid-template-columns:1fr}.profile{grid-template-columns:1fr}.top{align-items:flex-start;gap:10px}.shell{padding:18px 14px}}
</style></head><body><main class="shell"><header class="top"><div class="brand"><i class="mark"></i>OpsNest <span class="tag">Workspace</span></div><button id="logout" class="quiet hidden">Sign out</button></header>
<section id="loginView" class="card login"><div class="tag">Secure company access</div><h1>One place for the owner, accountant and team.</h1><p class="muted">Use the central team account created in OpsNest Desktop. Financial documents remain protected in the company workspace.</p><form id="loginForm"><label>Workspace ID<input id="workspaceId" autocomplete="organization" required placeholder="UUID from OpsNest Desktop"></label><label>Business e-mail<input id="email" type="email" autocomplete="email" required></label><label>Password<input id="password" type="password" autocomplete="current-password" required></label><div class="actions"><button class="primary" type="submit">Open workspace</button></div><button id="showReset" class="link" type="button">Forgot password?</button><p id="loginError" class="error"></p></form><form id="resetForm" class="hidden"><p class="muted">We will send a six-digit, one-time code to the business e-mail. Existing sessions will be signed out after the password changes.</p><label>Workspace ID<input id="resetWorkspaceId" required></label><label>Business e-mail<input id="resetEmail" type="email" required></label><label>Recovery code<input id="resetCode" inputmode="numeric" maxlength="6"></label><label>New password<input id="resetPassword" type="password" minlength="10"></label><div class="actions"><button id="sendReset" class="quiet" type="button">Send recovery code</button><button class="primary" type="submit">Set new password</button></div><button id="backToLogin" class="link" type="button">Back to sign in</button><p id="resetStatus" class="error"></p></form></section>
<section id="appView" class="hidden"><div class="hero"><div class="tag" style="color:#a9f5e8">Connected workspace</div><h1 id="companyName">Your OpsNest workspace</h1><p id="heroCopy">Loading collaboration controls…</p></div><div id="metrics" class="grid"></div><div class="two"><section class="card section"><h2>Platform modules</h2><div id="modules"></div></section><section class="card section"><h2>Company country pack</h2><p id="countrySummary" class="muted"></p><form id="profileForm" class="profile hidden"><label>Country code<select id="countryCode"><option value="RS">Serbia</option><option value="BG">Bulgaria</option><option value="HR">Croatia</option><option value="BA">Bosnia and Herzegovina</option><option value="ME">Montenegro</option><option value="MK">North Macedonia</option><option value="SI">Slovenia</option><option value="INTL">International</option></select></label><label>Currency<input id="currency" maxlength="8"></label><label class="wide">Business profile<select id="profile"><option value="general">General business</option><option value="construction">Construction</option><option value="services">Services</option><option value="trade">Trade</option></select></label><button class="primary wide" type="submit">Save platform profile</button></form></section></div><p class="footer">OpsNest Workspace shows secure collaboration metadata. Invoices, attachments and accounting records are never rendered in this browser portal without a dedicated country-specific module.</p></section>
</main><script>
const $=id=>document.getElementById(id),saved=()=>JSON.parse(sessionStorage.getItem('opsnestWorkspaceSession')||'null');let session=saved();
const esc=value=>String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
const headers=()=>({'Content-Type':'application/json','Authorization':'Bearer '+session.member_token,'X-OpsNest-Workspace':session.workspace_id,'X-OpsNest-Member':session.member_id});
async function api(path,options={}){const response=await fetch(path,{...options,headers:{...headers(),...(options.headers||{})}});const body=await response.json().catch(()=>({}));if(!response.ok)throw Error(body.detail||'The workspace request could not be completed.');return body;}
function showApp(data){$('loginView').classList.add('hidden');$('appView').classList.remove('hidden');$('logout').classList.remove('hidden');$('companyName').textContent=data.workspace.company_name||'OpsNest workspace';$('heroCopy').textContent=`${data.member.role_label} • ${data.workspace.country_label} • ${data.workspace.country_pack_stage}`;
 const sync=data.sync.enabled?`Revision ${data.sync.revision}`:'Not connected yet';$('metrics').innerHTML=[['Plan',data.license.effective_plan_code||data.license.plan_code],['Team seats',`${data.team.seats_used} / ${data.team.seat_limit}`],['Cloud sync',sync],['Role',data.member.role_label]].map(([label,value])=>`<article class="card metric"><span>${esc(label)}</span><b>${esc(value)}</b></article>`).join('');
 $('modules').innerHTML=data.modules.map(module=>`<div class="module"><div><b>${esc(module.title)}</b><p>${esc(module.detail)}</p></div><span class="status ${module.state==='foundation'?'foundation':''}">${esc(module.state)}</span></div>`).join('');
 $('countrySummary').textContent=`${data.workspace.country_label} (${data.workspace.country_code}) · ${data.workspace.default_currency}. ${data.workspace.country_pack_stage}.`;
 const canEdit=Boolean(data.team.can_manage);$('profileForm').classList.toggle('hidden',!canEdit);if(canEdit){$('countryCode').value=data.workspace.country_code;$('currency').value=data.workspace.default_currency;$('profile').value=data.workspace.business_profile;}}
async function load(){try{showApp(await api('/v1/workspace/overview'));}catch(error){session=null;sessionStorage.removeItem('opsnestWorkspaceSession');$('loginView').classList.remove('hidden');$('appView').classList.add('hidden');$('logout').classList.add('hidden');$('loginError').textContent=error.message;}}
$('loginForm').addEventListener('submit',async event=>{event.preventDefault();$('loginError').textContent='';try{const response=await fetch('/v1/team/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({workspace_id:$('workspaceId').value.trim(),email:$('email').value.trim(),password:$('password').value,device_name:'OpsNest Workspace Portal'})});const data=await response.json();if(!response.ok)throw Error(data.detail||'Sign-in failed.');session={workspace_id:data.workspace_id,member_id:data.member_id,member_token:data.member_token};sessionStorage.setItem('opsnestWorkspaceSession',JSON.stringify(session));await load();}catch(error){$('loginError').textContent=error.message;}});
$('showReset').addEventListener('click',()=>{$('loginForm').classList.add('hidden');$('resetForm').classList.remove('hidden');$('resetWorkspaceId').value=$('workspaceId').value.trim();$('resetEmail').value=$('email').value.trim();$('resetStatus').textContent='';});
$('backToLogin').addEventListener('click',()=>{$('resetForm').classList.add('hidden');$('loginForm').classList.remove('hidden');$('resetStatus').textContent='';});
$('sendReset').addEventListener('click',async()=>{const workspace_id=$('resetWorkspaceId').value.trim(),email=$('resetEmail').value.trim();$('resetStatus').className='muted';$('resetStatus').textContent='Sending recovery code…';try{const response=await fetch('/v1/team/password-reset/request',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({workspace_id,email})});const data=await response.json();if(!response.ok)throw Error(data.detail||'Recovery request could not be completed.');$('resetStatus').className='muted';$('resetStatus').textContent=data.message;}catch(error){$('resetStatus').className='error';$('resetStatus').textContent=error.message;}});
$('resetForm').addEventListener('submit',async event=>{event.preventDefault();$('resetStatus').className='muted';$('resetStatus').textContent='Changing password…';try{const response=await fetch('/v1/team/password-reset/confirm',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({workspace_id:$('resetWorkspaceId').value.trim(),email:$('resetEmail').value.trim(),code:$('resetCode').value.trim(),password:$('resetPassword').value})});const data=await response.json();if(!response.ok)throw Error(data.detail||'Password could not be changed.');$('workspaceId').value=$('resetWorkspaceId').value.trim();$('email').value=$('resetEmail').value.trim();$('password').value='';$('resetForm').classList.add('hidden');$('loginForm').classList.remove('hidden');$('loginError').textContent=data.message;}catch(error){$('resetStatus').className='error';$('resetStatus').textContent=error.message;}});
$('profileForm').addEventListener('submit',async event=>{event.preventDefault();try{showApp(await api('/v1/workspace/profile',{method:'POST',body:JSON.stringify({country_code:$('countryCode').value,default_currency:$('currency').value, business_profile:$('profile').value})}));}catch(error){alert(error.message);}});
$('logout').addEventListener('click',()=>{session=null;sessionStorage.removeItem('opsnestWorkspaceSession');$('loginView').classList.remove('hidden');$('appView').classList.add('hidden');$('logout').classList.add('hidden');$('password').value='';});if(session)load();
</script></body></html>"""
